### ISSUE TITLE
gta sa steam isue

### ISSUE THREAD

**Issue by matheusroquestr** [ThirteenAG/limit_adjuster_gta3vcsa#22]
when i start a new game, the game stops on the first game message and crash, and cj are invisible in mission cutscenes

**Comment by thelink2012** [comment]
Steam version is not supported.

**Comment by matheusroquestr** [comment]
i tested with a normal gta san andreas and i have the same problem...

**Comment by thelink2012** [comment]
AFAIK your game is terrible broken as of this thread in GTAF
http://gtaforums.com/topic/768065-gta-sa-crashing-help/#entry1067005475
Which makes me believe your problem has nothing to do with this project.

**Comment by matheusroquestr** [comment]
i tried today unistalling all my cleos, and other asi mods, runing only your limit adjuster, cj is still invisible in cutscenes, and when i start a new game the game crashes, i tested with steam gta sa version and normal gta sa, both of them are not working...

**Comment by matheusroquestr** [comment]
if you test on your gta you will see, you will have the same problem...
